# On garde le preload tel quel (obligatoire)
preload = /home/max/Images/village.png
preload = ~/Images/86nm4qk3ukag1.jpeg
preload = ~/Images/i2smwge76o9g1.jpeg
preload = ~/Images/76tao56d797g1.png
preload = ~/Images/wck5j2bcspfg1.jpeg
preload = ~/Images/zebra.jpg

wallpaper {
    monitor = DP-3
    path = ~/Images/wck5j2bcspfg1.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Images/zebra.jpg
    fit_mode = cover
}

splash = false

